"""Validate the public bilingual READMEs and generated screenshot contract."""

from __future__ import annotations

import hashlib
import re
import struct
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
READMES = (ROOT / "README.md", ROOT / "README_EN.md")
IMAGE_NAMES = (
    "launchflow-workbench-dark.png",
    "launchflow-workbench-light.png",
    "launchflow-step-reorder.png",
    "launchflow-log-console.png",
    "launchflow-plan-history.png",
    "launchflow-export-workflow.png",
)


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def png_size(path: Path) -> tuple[int, int]:
    raw = path.read_bytes()
    require(raw.startswith(b"\x89PNG\r\n\x1a\n"), f"not a PNG: {path}")
    return struct.unpack(">II", raw[16:24])


def check_local_links(path: Path, text: str) -> None:
    for target in re.findall(r"\[[^\]]+\]\(([^)]+)\)", text):
        if target.startswith(("http://", "https://", "mailto:", "#")):
            continue
        clean_target = target.split("#", 1)[0]
        require((path.parent / clean_target).resolve().exists(), f"broken local link in {path.name}: {target}")


def main() -> int:
    texts = {path.name: path.read_text(encoding="utf-8") for path in READMES}
    require(all(len(text) >= 6_000 for text in texts.values()), "a README is too short to be a complete project introduction")
    require(
        texts["README.md"].startswith("# 🚀 LaunchFlow\n\n**[简体中文](./README.md)** | [English](./README_EN.md)"),
        "Chinese language switch is missing or misplaced",
    )
    require(
        texts["README_EN.md"].startswith("# 🚀 LaunchFlow\n\n[简体中文](./README.md) | **[English](./README_EN.md)**"),
        "English language switch is missing or misplaced",
    )

    required_content = {
        "README.md": (
            "## 🙏 特别致谢",
            "ZTS",
            "SYZ",
            "4 位同学",
            "[查看更新日志](./CHANGELOG.md)",
        ),
        "README_EN.md": (
            "## 🙏 Acknowledgements",
            "ZTS",
            "SYZ",
            "four students",
            "[View changelog](./CHANGELOG.md)",
        ),
    }
    for readme, markers in required_content.items():
        for marker in markers:
            require(marker in texts[readme], f"required public README content missing in {readme}: {marker}")

    forbidden = (
        r"F:\\Codex",
        r"C:\\Users\\",
        r"E:\\code",
        "private/private_key.pem",
        "private_key.pem",
        "generated by AI",
        "AI-generated documentation",
        "insert screenshot here",
        "this section should contain",
        "placeholder",
        "TODO",
        "TBD",
        "待补充",
        "此处插入截图",
        "这里应该写",
        "请在这里补充",
    )
    combined = "\n".join(texts.values())
    for marker in forbidden:
        require(marker.lower() not in combined.lower(), f"forbidden public README marker: {marker}")
    require(not re.search(r"LFREQ1\.[A-Za-z0-9_-]{20,}", combined), "full request token leaked into README")
    require(not re.search(r"<!--[\s\S]*?-->", combined), "HTML writing comment leaked into README")
    require(
        not re.search(r"\b(?:MIT License|Apache License|GNU General Public License|GPL)\b", combined, re.IGNORECASE),
        "unsupported open-source license claim in README",
    )

    heading_contract = {
        "README.md": ("## ✨ 为什么做 LaunchFlow", "## 🌟 核心能力", "## 📄 许可"),
        "README_EN.md": ("## ✨ Why LaunchFlow", "## 🌟 Core Features", "## 📄 License"),
    }
    for readme, headings in heading_contract.items():
        for heading in headings:
            require(heading in texts[readme], f"main heading icon contract missing in {readme}: {heading}")

    for readme, text in texts.items():
        require(text.count("```") % 2 == 0, f"unbalanced code fence in {readme}")
        require("v0.1.0-beta.2" in text and "0.1.0-beta" in text, f"version distinction missing in {readme}")
        require("application" in text.lower() and "command" in text.lower() and "wait" in text.lower(), f"step types missing in {readme}")
        require("licensing/" in text and "tools/build_single_exe.py" in text, f"real repository layout missing in {readme}")
        require("exporter/" not in text.split("```text", 1)[1].split("```", 1)[0], f"nonexistent exporter directory listed in {readme}")
        require("license/" not in text.split("```text", 1)[1].split("```", 1)[0], f"incorrect license directory listed in {readme}")
        require("all rights reserved" in text.lower(), f"all-rights-reserved license statement missing in {readme}")
        check_local_links(ROOT / readme, text)

    require((ROOT / "LICENSE").is_file(), "README license link requires repository LICENSE")

    image_hashes: set[str] = set()
    for name in IMAGE_NAMES:
        path = ROOT / "docs" / "images" / name
        require(path.is_file() and path.stat().st_size > 10_000, f"missing or empty screenshot: {name}")
        width, height = png_size(path)
        minimum = (1000, 360) if name == "launchflow-log-console.png" else (1200, 760)
        require(width >= minimum[0] and height >= minimum[1], f"screenshot is too small: {name} ({width}x{height})")
        image_hashes.add(hashlib.sha256(path.read_bytes()).hexdigest())
        for text in texts.values():
            require(f"docs/images/{name}" in text, f"screenshot is not used by both READMEs: {name}")
    require(len(image_hashes) == len(IMAGE_NAMES), "README screenshots are not visually distinct files")

    print("readme docs smoke ok")
    print("languages=zh-CN,en")
    print("screenshots=6,distinct,png,feature-sized")
    print("public-paths=local-machine-paths-absent")
    print("placeholders=absent")
    print("acknowledgements=four-testers,zts,syz")
    print("repository-layout=real-directories")
    print("license=all-rights-reserved,linked")
    print("local-links=resolved")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
